### ISSUE TITLE
rust model: reorganize the models

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/keth#111]
At the moment, all the keth model in rust are stored in this single file: https://github.com/kkrt-labs/keth/blob/bd14d973f19314bb5cb246aaff6ceab3e4d8f65f/crates/exex/src/model.rs

It is starting to become quite big and it would be good to split it into several files in a `model` folder:
- general primitives :`KethU256`, `KethMaybeRelocatable`, `KethOption`...
- block header model: `KethBlockHeader`
- transaction model: `KethTransactionEncoded`

With this new division, we would have a more modular and scalable structure with small modules

**Comment by varun-doshi** [comment]
I can take this up

**Comment by tcoratger** [comment]
> I can take this up

@varun-doshi Sorry forgot to link the issue, already closed by https://github.com/kkrt-labs/keth/pull/116

But soon we will have more good first issues, will tag you if you want

**Comment by varun-doshi** [comment]
> > I can take this up
> 
> @varun-doshi Sorry forgot to link the issue, already closed by #116
> 
> But soon we will have more good first issues, will tag you if you want

Looking forward to the next issues
Thanks
