### ISSUE TITLE
fix: extcodehash refactor

### ISSUE THREAD

**Issue by obatirou** [kkrt-labs/keth#165]
https://github.com/kkrt-labs/kakarot/pull/1644 supersed by https://github.com/kkrt-labs/kakarot/pull/1654

**Comment by enitrat** [comment]
for keth, the codehash should be a part of the initial state given to the program

**Comment by enitrat** [comment]
@ClementWalter, @obatirou : nothing to do here as fixes to apply were related to starknet, and thus, not relevant in the context of keth
