### ISSUE TITLE
Add `gen_arg` test with arbitrary block

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/keth#182]
In https://github.com/kkrt-labs/keth/pull/127, we tested the `KethPayload` function with a simplified harcoded block for which we knew exactly the expected behavior:

https://github.com/kkrt-labs/keth/blob/a143261016181723e92db7b58fda13772d1d33ec/crates/exex/src/model/payload.rs#L613-L1095

Now that this check is done, it would be beneficial to add another test below with an arbitrary block in order to add an even larger and arbitrary test coverage while keeping the harcoded test which will serve as a reference for the implementation and for us in the future (as the test is simplified, it is easy to navigate and understand if there is a problem).

cc  @varun-doshi maybe you could be interested by this one

**Comment by varun-doshi** [comment]
Yes I can take this up

**Comment by tcoratger** [comment]
> Yes I can take this up

Perfect, assigned
