### ISSUE TITLE
feat: `get_account` should return a new, empty account if not in the initial state

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/keth#243]
If an account is first interacted with during the transaction that applies the state transition `STF(S, S')` and an account part of S' is not in the input S, then calling `get_account` will cast 0 to a `model.Account*` which is incorrect.

This scenario could happen when the first interaction with an account happens in the transaction. ~Because the account is not part of state S before the transaction, it's not required to have it as part of the sparse MPT given as input to compute the new root.~

**Comment by ClementWalter** [comment]
we actually need to return

```
EMPTY_ACCOUNT = Account(
    nonce=Uint(0),
    balance=U256(0),
    code=bytearray(),
)
```

but I've ~strike through~ the MPT part as it's not so simlpe
