### ISSUE TITLE
ci: run nightly CI with logs

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#259]
## Why

When the nightly CI fails, there is no log to actually reproduce the failing example, see for example 
https://github.com/kkrt-labs/keth/actions/runs/12287505621/job/34289650881

## What

Change the log level to debug

## How

Run pytest with `-s --hypothesis-verbosity=debug`

**Comment by obatirou** [comment]
Seems related to too much log https://github.com/pytest-dev/pytest-xdist/issues/1138
Passing `--hypothesis-verbosity=debug` will only increase it and it is not manageable (in local for a few tests, this is illisible).

Reproducing the 1500 runs in local shows that the function that cause the exeception is using a lot of memory 
(20go in under 2min)

`load_packed_bytes` is not used relevant in Keth anymore as it was part of the account of Kakarot.

I think the problems comes from the fact there is no upper bound or filtering in the length of the input leading to enormous input data (and increase in memory consumption-
```
 @given(bytes=st.binary(min_size=1))
    def test_should_raise_zellic_issue_1283_load_packed_bytes(
        self, cairo_program, cairo_run, bytes: Bytes
    ):
        packed_bytes = pack_calldata(bytes)
        with (
```

Will remove this function.
