### ISSUE TITLE
feat: fix default_dict_copy cannot handle non-default initial value

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/keth#57]
### Why

The utils comes from Kakarot. In Kakarot, and in the default hints of the cairo vm, default_dict cannot be created with an initial dict.
However, in Keth, we do use default dict for storage and accounts (because empty storage and account should return 0) but they are populated with the prev state as initial values.

### What

Update the utils, writing a hint, to circumvent this limitatoin.

### How

It seems that the easiest is to copy the memory segment into a new segment and update the dict manager in a hint such that it's recognizes as a default_dict.

Note that the concept of "default value" makes no sense from the CairoVM pov where dict are more like logs of memory accesses.

**Comment by MohamadSafi** [comment]
Hi team,

I'd like to work on this issue and want to confirm my understanding and proposed solution.

**Issue Understanding:**

In Keth, we use `default_dicts` for storage and accounts, which return `0` for unset keys. However, we need to initialize these `default_dicts` with existing state values (e.g., previous blockchain state). Currently, Cairo's `default_dict` cannot be initialized with pre-set key-value pairs—it only starts empty with a default value for missing keys. This limitation hinders us from setting up the initial state correctly in Keth.

**Proposed Solution:**

1. Custom Hint:
          - Develop a hint to initialize a `default_dict` with predefined key-value pairs.
          - This hint will copy initial data into the `default_dict` and adjust internal structures for Cairo VM recognition.
        
2. Memory Segment Copy:
          - Use the hint to copy existing memory segments with initial data into new segments.
          - Update the dict manager to recognize these as `default_dicts`.

3. Dict Manager Adjustment:
          - Modify the dict manager to treat new segments as `default_dicts` with initial values.
          - Preserve the default behavior of returning `0` for unset keys.

**Relevant Files:**

- Utilities:
        `cairo/src/utils/utils.cairo`
        `cairo/src/utils/dict.cairo `

- State and Account Management:
        `cairo/src/state.cairo`
        `cairo/src/account.cairo`

- Files Using default_dict:
        `cairo/src/evm.cairo`
        `cairo/src/interpreter.cairo`
        `cairo/src/memory.cairo`
        `cairo/src/stack.cairo`
        `cairo/src/instructions/system_operations.cairo`
        `cairo/src/precompiles/ripemd160.cairo`

Request:

Before proceeding, I'd like to confirm that my understanding aligns with the team's expectations and that this proposed solution is acceptable. Please let me know if I can contribute to this issue.

Best regards,

**Comment by ClementWalter** [comment]
hey @MohamadSafi , thanks for your interest in working on keth! I'm sorry because this issue was indeed already solved but not marked as is. I'm opening and scoping new issues now so that you can apply to others

**Comment by MohamadSafi** [comment]
Alright no problem.
I will be looking out for more issues 😁
