### ISSUE TITLE
Create architecture diagram

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/keth#6]
Create architecture diagram

**Comment by ClementWalter** [comment]
See https://app.excalidraw.com/l/8WWU7eJs953/7Z1ERfCFkzp

**Comment by Eikix** [comment]
> See https://app.excalidraw.com/l/8WWU7eJs953/7Z1ERfCFkzp

why are there two diagrams? they're alternative designs?

**Comment by ClementWalter** [comment]
same design, just one with a single Reth block, the other with detailed content. not sure which is best but it's the same eventually
